// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Xk-WzQYCotrF1hyrRyMWbaEFr8DZiE8',
    appId: '1:645040820402:web:242fabd2be4cdacc5479ab',
    messagingSenderId: '645040820402',
    projectId: 'registration-backend-ba673',
    authDomain: 'registration-backend-ba673.firebaseapp.com',
    storageBucket: 'registration-backend-ba673.firebasestorage.app',
    measurementId: 'G-CQKG59LZ10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRpmLqK-PCHnMhO2MoYKDrWmhqC6bWP74',
    appId: '1:645040820402:android:041124a4bde9a3855479ab',
    messagingSenderId: '645040820402',
    projectId: 'registration-backend-ba673',
    storageBucket: 'registration-backend-ba673.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoT36wieS7NuTkNwyVojAsHai7C0xNn_0',
    appId: '1:645040820402:ios:7c6175a9fd2100815479ab',
    messagingSenderId: '645040820402',
    projectId: 'registration-backend-ba673',
    storageBucket: 'registration-backend-ba673.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoT36wieS7NuTkNwyVojAsHai7C0xNn_0',
    appId: '1:645040820402:ios:7c6175a9fd2100815479ab',
    messagingSenderId: '645040820402',
    projectId: 'registration-backend-ba673',
    storageBucket: 'registration-backend-ba673.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Xk-WzQYCotrF1hyrRyMWbaEFr8DZiE8',
    appId: '1:645040820402:web:8e46487e16814e285479ab',
    messagingSenderId: '645040820402',
    projectId: 'registration-backend-ba673',
    authDomain: 'registration-backend-ba673.firebaseapp.com',
    storageBucket: 'registration-backend-ba673.firebasestorage.app',
    measurementId: 'G-66E03F90F8',
  );
}
